Repository theodo/castore, pull requests merged in 2022-07, with the labels that each got.

#57 feature: small refacto in inMemory adapter
  packages/event-store/src/eventStore.util.test.ts
  packages/event-store/src/storageAdapter/implementations/inMemory.ts
  packages/event-store/tsconfig.json
Labels: minor

#52 feature: remove dynamodb toolbox from dynamodb event storage adapter
  castore.code-workspace
  demo/blueprint/src/commands/createUser.ts
  demo/blueprint/src/commands/deleteUser.ts
  demo/blueprint/src/index.ts
  demo/implementation/functions/createUser/handler.ts
  demo/implementation/functions/createUser/index.ts
  demo/implementation/functions/deleteUser/handler.ts
  demo/implementation/functions/deleteUser/index.ts
  demo/implementation/functions/getCounterEvents/handler.ts
  demo/implementation/functions/getCounterEvents/index.ts
  demo/implementation/functions/index.ts
  demo/implementation/functions/logAggregateIds/handler.ts
  demo/implementation/functions/logAggregateIds/index.ts
  demo/implementation/functions/logUserEvents/handler.ts
  demo/implementation/functions/logUserEvents/index.ts
  demo/implementation/functions/logUserEvents/schema.ts
  demo/implementation/libs/eventStores/client.ts
  demo/implementation/libs/eventStores/counters.ts
  demo/implementation/libs/eventStores/users.ts
  demo/implementation/package.json
  demo/implementation/resources/dynamoDB/counterEventsTable.ts
  demo/implementation/resources/dynamoDB/eventTableKeys.ts
  demo/implementation/resources/dynamoDB/userEventsTable.ts
  demo/implementation/serverless.ts
  demo/implementation/tsconfig.json
  demo/visualization/src/index.tsx
  packages/dynamodb-event-storage-adapter/package.json
  packages/dynamodb-event-storage-adapter/src/dynamoDb.ts
  workspace.json
  yarn.lock
Labels: minor

#65 feature: hardly type event store ids
  demo/implementation/tsconfig.tsbuildinfo
  demo/visualization/tsconfig.tsbuildinfo
  packages/core/src/eventStore.ts
  packages/core/src/eventStore.type.test.ts
Labels: minor

#66 feature: 🤡 Mock event store
  .github/workflows/realease-to-npm.yml
  castore.code-workspace
  demo/blueprint/src/counters/index.ts
  demo/blueprint/src/counters/mock.ts
  packages/test-tools/.eslintignore
  packages/test-tools/.eslintrc.js
  packages/test-tools/.lintstagedrc.js
  packages/test-tools/babel.config.js
  packages/test-tools/dependency-cruiser.js
  packages/test-tools/jest.config.js
  packages/test-tools/package.json
  packages/test-tools/project.json
  packages/test-tools/src/index.ts
  packages/test-tools/src/mockEventStore.ts
  packages/test-tools/src/mockEventStore.type.test.ts
  packages/test-tools/src/mockEventStore.unit.test.ts
  packages/test-tools/tsconfig.build.json
  packages/test-tools/tsconfig.json
  workspace.json
  yarn.lock
Labels: major

#67 feature: small improve of abstract event store definitions type
  packages/core/src/eventStore.ts
Labels: minor

#64 feature: list aggregate ids pagination
  babel.config.js
  commonConfiguration/babel.config.js
  packages/core/src/eventStore.ts
  packages/core/src/index.ts
  packages/core/src/storageAdapter.ts
  packages/dynamodb-event-storage-adapter/src/dynamoDb.ts
  packages/dynamodb-event-storage-adapter/src/utils/parseAppliedListAggregateIdsOptions.ts
  packages/inmemory-event-storage-adapter/src/inMemory.ts
  packages/inmemory-event-storage-adapter/src/inMemory.unit.test.ts
  packages/inmemory-event-storage-adapter/src/utils/parseAppliedListAggregateIdsOptions.ts
Labels: minor

#71 fix: release inmemory storage adapter to npm
  .github/workflows/realease-to-npm.yml
Labels: patch

#72 chore: import logo assets
  README.md
  assets/logo-license.pdf
  assets/logo.ai
  assets/logo.svg
Labels: ignore-for-release

#78 fix: fix release script 1
  .github/workflows/draft-or-update-next-release.yml
  .github/workflows/label-pr.yml
  .github/workflows/realease-to-npm.yml
Labels: patch

#81 fix: fix release script 3
  .github/workflows/realease-to-npm.yml
  .github/workflows/release-to-npm.yml
  .gitignore
  demo/blueprint/package.json
  demo/implementation/package.json
  demo/visualization/package.json
  lerna.json
  package.json
  packages/core/package.json
  packages/dynamodb-event-storage-adapter/package.json
  packages/dynamodb-event-storage-adapter/src/dynamoDb.ts
  packages/inmemory-event-storage-adapter/package.json
  packages/json-schema-event/package.json
  packages/test-tools/package.json
  packages/zod-event/package.json
  scripts/setPackagesVersions.ts
  yarn.lock
Labels: patch

#82 fix: fix release script 4
  .github/workflows/release-to-npm.yml
  scripts/setPackagesVersions.ts
Labels: patch

#83 fix: fix release script (5)
  scripts/setPackagesVersions.ts
Labels: patch

#76 chore: copy-paste root README to core before release
  .github/workflows/release-to-npm.yml
Labels: minor
